### ISSUE TITLE
how we can install it ?

### ISSUE THREAD

**Issue by eguvenc** [angelozerr/mongo-mapreduce-webbrowser#12]
is there any docs for installation ?

**Comment by angelozerr** [comment]
I have not written docs because the API should change (save/load MapReduce js from the server). But if you know Java and Maven, is very easy. Import the project in your Eclipse Project and launch the StartServer https://github.com/angelozerr/mongo-mapreduce-webbrowser/blob/master/src/test/java/fr/opensagres/mapreduce/webbrowser/StartServer.java main. 

It launchs a Jetty Server on 8081 port and you can access it to the URL localhost:8081/mongo

The server side is very simply and I think we could manage the server with other technologies like PHP, Node.js, etc. If you are interested, tell me.

Perhaps a distribution with bat/sh should be done?

**Comment by pascalleclercq** [comment]
Here is what I suggest :
java -jar mongo-mapreduce-webbrowser-0.0.1-SNAPSHOT-runner.war

where is the version 

then open a browser :

http://localhost:12345/ (port: 12345, no  webapp context)

**Comment by pascalleclercq** [comment]
alternatively we may remove the version in the war file name 

eg : java -jar mongo-mapreduce-webbrowser-runner.war

**Comment by angelozerr** [comment]
Thank's Pascal for your suggestion.

I think we should have 2 distributions : 

1) a classic war mongo-mapreduce-webbrowser.war which doesn't contains the StartServer class.
2) a jar mongo-mapreduce-webbrowser-runner.war which contains the StartServer like you have suggested. I think it should be cool if the StartServer main could be call with 2 optionnal args : 
- "-port" : to specify the port
- "-contextpath" : to specify the webapp context.

For instance we could call StartServer like this : 

java -jar mongo-mapreduce-webbrowser-runner.war

then open a browser :

http://localhost:12345/ (port: 12345, no webapp context)

or 

eg : java -jar mongo-mapreduce-webbrowser-runner.war -port 8081 - contextpath mapreduces

then open a browser :

http://localhost:8081/mapreduces

This distribtribution should contains several commands files :
- start.cmd which call mongo-mapreduce-webbrowser-runner.war for Windows OS 
- start.sh which call mongo-mapreduce-webbrowser-runner.war for Linux OS

**Comment by pascalleclercq** [comment]
Done

**Comment by pascalleclercq** [comment]
reopining as some more feature to come...

**Comment by angelozerr** [comment]
See doc at https://github.com/angelozerr/mongo-mapreduce-webbrowser/wiki/Installation-Guide
